version: '3'
services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/something-something.json
      - DGRAPH_HOST=https://something-something.eu-central-1.aws.cloud.dgraph.io
      - DGRAPH_KEY=something
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app